USE FoodDelivery_SourceDB;
GO

-- Insert into src.Restaurant (50 clean rows)
INSERT INTO src.Restaurant (RestaurantID, Name, City, Area, CuisineType, Rating) VALUES
(71001, 'Burger King Manhattan', 'New York', 'Manhattan', 'Fast Food', 4.2),
(71002, 'Sushi House LA', 'Los Angeles', 'Downtown LA', 'Asian Cuisine', 4.5),
(71003, 'Pizza Hut Chicago', 'Chicago', 'Lincoln Park', 'Western Cuisine', 4.1),
(71004, 'Spicy Curry Houston', 'Houston', 'Midtown', 'Asian Cuisine', 4.4),
(71005, 'Steak House SF', 'San Francisco', 'Mission District', 'Western Cuisine', 4.3),
(71006, 'Pasta Palace Brooklyn', 'New York', 'Brooklyn', 'Western Cuisine', 4.0),
(71007, 'Tokyo Sushi SD', 'San Diego', 'Gaslamp', 'Asian Cuisine', 4.6),
(71008, 'Tex Mex BBQ Houston', 'Houston', 'Galleria', 'Mexican', 4.2),
(71009, 'Vegan Garden Hollywood', 'Los Angeles', 'Hollywood', 'Vegan Options', 4.1),
(71010, 'Cake World Chicago', 'Chicago', 'Hyde Park', 'Desserts', 4.3),
(71011, 'King Burger Dallas', 'Dallas', 'Deep Ellum', 'Fast Food', 4.0),
(71012, 'Golden Dragon NY', 'New York', 'Chinatown', 'Asian Cuisine', 4.5),
(71013, 'BBQ Pit Houston', 'Houston', 'Downtown', 'Western Cuisine', 4.1),
(71014, 'The Burrito Spot LA', 'Los Angeles', 'East LA', 'Mexican', 4.4),
(71015, 'Pancake House Chicago', 'Chicago', 'Wicker Park', 'Breakfast', 4.2),
(71016, 'Green Vegan SF', 'San Francisco', 'Castro', 'Vegan Options', 4.3),
(71017, 'Bagel Bros NY', 'New York', 'Chelsea', 'Bakery', 4.2),
(71018, 'Seafood Shack LA', 'Los Angeles', 'Santa Monica', 'Seafood', 4.5),
(71019, 'Taco Town Houston', 'Houston', 'Montrose', 'Mexican', 4.1),
(71020, 'Doughnut Delight Chicago', 'Chicago', 'River North', 'Bakery', 4.0),
(71021, 'Morning Coffee House SF', 'San Francisco', 'SoMa', 'Beverages', 4.3),
(71022, 'Toast & Jam NY', 'New York', 'SoHo', 'Breakfast', 4.1),
(71023, 'Little Tokyo Sushi LA', 'Los Angeles', 'Little Tokyo', 'Asian Cuisine', 4.5),
(71024, 'Crusty Pizza Houston', 'Houston', 'Rice Village', 'Western Cuisine', 4.2),
(71025, 'Sweet Tooth Bakery Chicago', 'Chicago', 'Uptown', 'Desserts', 4.4),
(71026, 'Fiesta Tacos SF', 'San Francisco', 'Mission', 'Mexican', 4.3),
(71027, 'Seaside Grilled Fish LA', 'Los Angeles', 'Venice', 'Seafood', 4.4),
(71028, 'Sunrise Breakfast NY', 'New York', 'Harlem', 'Breakfast', 4.0),
(71029, 'Big Apple Burger NY', 'New York', 'Upper East Side', 'Fast Food', 4.2),
(71030, 'La Baguette SF', 'San Francisco', 'Haight-Ashbury', 'Bakery', 4.3),
(71031, 'Vegan Nation Houston', 'Houston', 'West University', 'Vegan Options', 4.2),
(71032, 'Sake Sushi Chicago', 'Chicago', 'Old Town', 'Asian Cuisine', 4.5),
(71033, 'Morning Glory Cafe LA', 'Los Angeles', 'Brentwood', 'Breakfast', 4.3),
(71034, 'Quesadilla Queen Houston', 'Houston', 'Heights', 'Mexican', 4.1),
(71035, 'The Coffee Corner SF', 'San Francisco', 'Financial District', 'Beverages', 4.4),
(71036, 'Muffin Mania Chicago', 'Chicago', 'Edgewater', 'Bakery', 4.2),
(71037, 'The Waffle House LA', 'Los Angeles', 'Koreatown', 'Breakfast', 4.0),
(71038, 'Pasta Fresca Houston', 'Houston', 'Midtown', 'Western Cuisine', 4.2),
(71039, 'Sea Breeze Seafood SF', 'San Francisco', 'Fisherman’s Wharf', 'Seafood', 4.5),
(71040, 'Nacho Town Dallas', 'Dallas', 'Bishop Arts', 'Mexican', 4.1),
(71041, 'Avocado Vegan Cafe NY', 'New York', 'East Village', 'Vegan Options', 4.3),
(71042, 'Little Bakery Houston', 'Houston', 'Bellaire', 'Bakery', 4.2),
(71043, 'Sushi Garden SF', 'San Francisco', 'Japantown', 'Asian Cuisine', 4.6),
(71044, 'Happy Pancake House LA', 'Los Angeles', 'Downtown LA', 'Breakfast', 4.1),
(71045, 'Cupcake Delight Chicago', 'Chicago', 'Logan Square', 'Desserts', 4.3),
(71046, 'Classic BBQ Dallas', 'Dallas', 'Knox Henderson', 'Western Cuisine', 4.2),
(71047, 'The Croissant Spot NY', 'New York', 'Tribeca', 'Bakery', 4.5),
(71048, 'Pita Paradise Houston', 'Houston', 'Medical Center', 'Western Cuisine', 4.3),
(71049, 'Morning Java Chicago', 'Chicago', 'South Loop', 'Beverages', 4.4),
(71050, 'Fish Market SF', 'San Francisco', 'Embarcadero', 'Seafood', 4.5);
GO